@host = http://localhost:3333

### Lista orfanatos
GET {{host}}/orphanages HTTP/1.1

### Dados de um orfanato
GET {{host}}/orphanages/5 HTTP/1.1

### Cria novo orfanato
POST {{host}}/orphanages HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="images"; filename="1.jpeg"
Content-Type: image/jpeg

< ./1.jpeg
--MyBoundary
Content-Disposition: form-data; name="images"; filename="2.jpeg"
Content-Type: image/jpeg

< ./1.jpeg
--MyBoundary
Content-Disposition: form-data; name="name"

Lar da meninas
--MyBoundary
Content-Disposition: form-data; name="latitude"

-26.3378556
--MyBoundary
Content-Disposition: form-data; name="longitude"

-48.878686
--MyBoundary
Content-Disposition: form-data; name="about"

Sobre o orfanato
--MyBoundary
Content-Disposition: form-data; name="instructions"

Venha visitar
--MyBoundary
Content-Disposition: form-data; name="openingHours"

Das 8h até as 18h
--MyBoundary
Content-Disposition: form-data; name="openOnWeekends"

true
--MyBoundary--
